// lib/quotes.ts - Zetta Oracle Wisdom Archive with Authors (v5.0)
export const quotes = [
  "The happiness of your life depends upon the quality of your thoughts. — Marcus Aurelius",
  "Victorious warriors win first and then go to war. — Sun Tzu",
  "A man who conquers himself is greater than one who conquers a thousand men. — Gautama Buddha",
  "Fortune favors the bold. — Virgil",
  "He who has a why to live can bear almost any how. — Friedrich Nietzsche",
  "Difficulties strengthen the mind, as labor does the body. — Seneca",
  "To improve is to change. — Winston Churchill",
  "Energy and persistence conquer all things. — Benjamin Franklin",
  "The obstacle is the way. — Marcus Aurelius",
  "You must expect great things of yourself before you can do them. — Michael Jordan",
  "Courage is resistance to fear, mastery of fear. — Mark Twain",
  "Act as if what you do makes a difference. It does. — William James",
  "The harder the conflict, the greater the triumph. — George Washington",
  "Great spirits have always encountered violent opposition from mediocre minds. — Albert Einstein",
  "Fall seven times and stand up eight. — Japanese Proverb",
  "Do not pray for an easy life. Pray for the strength to endure a difficult one. — Bruce Lee",
  "No man is free who is not master of himself. — Epictetus",
  "Success is how high you bounce when you hit bottom. — George S. Patton",
  "Discipline is the bridge between goals and accomplishment. — Jim Rohn",
  "He who sweats more in training bleeds less in war. — Spartan Proverb",
  "Knowing yourself is the beginning of all wisdom. — Aristotle",
  "Strength comes from an indomitable will. — Mahatma Gandhi",
  "Never interrupt your enemy when he is making a mistake. — Napoleon Bonaparte",
  "If you’re going through hell, keep going. — Winston Churchill",
  "The best revenge is massive success. — Frank Sinatra",
  "A ship in harbor is safe, but that is not what ships are built for. — John A. Shedd",
  "The soul becomes dyed with the color of its thoughts. — Marcus Aurelius",
  "Victory belongs to the most persevering. — Napoleon Bonaparte",
  "The man who moves a mountain begins by carrying away small stones. — Confucius",
  "What we do in life echoes in eternity. — Marcus Aurelius",
  "Success usually comes to those who are too busy to be looking for it. — Henry David Thoreau",
  "Only those who dare to fail greatly can ever achieve greatly. — Robert F. Kennedy",
  "The greater the difficulty, the more glory in surmounting it. — Epicurus",
  "He who fears being conquered is sure of defeat. — Napoleon Bonaparte",
  "Do what you can, with what you have, where you are. — Theodore Roosevelt",
  "A smooth sea never made a skilled sailor. — Franklin D. Roosevelt",
  "The future depends on what you do today. — Mahatma Gandhi",
  "Great acts are made up of small deeds. — Laozi",
  "Without struggle, there is no progress. — Frederick Douglass",
  "The secret of getting ahead is getting started. — Mark Twain",
  "A hero is an ordinary individual who finds the strength to persevere. — Christopher Reeve",
  "The pain you feel today will be the strength you feel tomorrow. — Arnold Schwarzenegger",
  "Don’t count the days. Make the days count. — Muhammad Ali",
  "It always seems impossible until it’s done. — Nelson Mandela",
  "Dreams are important. You can’t do it unless you imagine it. — George Lucas",
  "Courage is grace under pressure. — Ernest Hemingway",
  "Do not wait to strike till the iron is hot; make it hot by striking. — William Butler Yeats",
  "Our greatest glory is in rising every time we fall. — Confucius",
  "Nothing splendid has ever been achieved except by those who dared believe. — Bruce Barton",
  "Adversity introduces a man to himself. — Albert Einstein",
  "The best way out is always through. — Robert Frost",
  "Tough times never last, but tough people do. — Robert H. Schuller",
  "Do one thing every day that scares you. — Eleanor Roosevelt",
  "A warrior lives by acting, not by thinking about acting. — Carlos Castaneda",
  "The secret of success is constancy to purpose. — Benjamin Disraeli",
  "You miss 100% of the shots you don’t take. — Wayne Gretzky",
  "There is no easy way from the earth to the stars. — Seneca",
  "Victory has a hundred fathers and defeat is an orphan. — John F. Kennedy",
  "Character is fate. — Heraclitus",
  "Strength grows in the moments when you think you can’t go on. — Unknown",
  "If opportunity doesn’t knock, build a door. — Milton Berle",
  "Only discipline will set you free. — Jocko Willink",
  "The successful warrior is the average man with laser-like focus. — Bruce Lee",
  "Action is the foundational key to all success. — Pablo Picasso",
  "Be faithful in small things because in them your strength lies. — Mother Teresa",
  "What lies within us is greater than what lies before us. — Ralph Waldo Emerson",
  "The future belongs to those who prepare for it today. — Malcolm X",
  "The only limit to our realization of tomorrow is our doubts of today. — Franklin D. Roosevelt",
  "Life shrinks or expands in proportion to one’s courage. — Anais Nin",
  "Fortune sides with him who dares. — Virgil",
  "The strongest people are forged by adversity. — Unknown",
  "Great things never came from comfort zones. — Unknown",
  "Difficult roads often lead to beautiful destinations. — Zig Ziglar",
  "The harder you work, the luckier you get. — Gary Player",
  "Success demands singleness of purpose. — Vince Lombardi",
  "One who overcomes obstacles possesses the strength to overcome adversity. — Albert Schweitzer",
  "The will to win means nothing without the will to prepare. — Juma Ikangaa",
  "The difference between ordinary and extraordinary is that little extra. — Jimmy Johnson",
  "Strength and growth come only through continuous effort. — Napoleon Hill",
  "Hardships often prepare ordinary people for an extraordinary destiny. — C. S. Lewis",
  "Never let the fear of striking out keep you from playing the game. — Babe Ruth",
  "Don’t watch the clock; do what it does. Keep going. — Sam Levenson",
  "A river cuts through rock because of persistence. — James Watkins",
  "Work hard in silence, let success make the noise. — Frank Ocean",
  "It does not matter how slowly you go as long as you do not stop. — Confucius",
  "The pain of discipline is far less than the pain of regret. — Jim Rohn",
  "A man can be destroyed but not defeated. — Ernest Hemingway",
  "You cannot swim for new horizons until you have courage to lose the shore. — William Faulkner",
  "A warrior accepts his pain and endures it. — Miyamoto Musashi",
  "Opportunity is often dressed in overalls and looks like work. — Thomas Edison",
  "Success is where preparation and opportunity meet. — Bobby Unser",
  "What consumes your mind controls your life. — Marcus Aurelius",
  "Great works are performed not by strength but by perseverance. — Samuel Johnson",
  "The secret of change is to focus energy on building the new. — Socrates",
  "It is during our darkest moments that we must focus to see the light. — Aristotle",
  "One day the people that didn’t believe in you will tell how they met you. — Johnny Depp",
  "Don’t limit your challenges. Challenge your limits. — Jerry Dunn",
  "The strongest steel is forged in the hottest fire. — Richard Nixon",
  "A goal without a plan is just a wish. — Antoine de Saint-Exupery",
  "Failure is simply the opportunity to begin again. — Henry Ford",
  "Success isn’t owned, it’s leased. — J. J. Watt",
  "When you feel like quitting, remember why you started. — Unknown",
  "Don’t stop when you’re tired. Stop when you’re done. — Marilyn Monroe",
  "If you want greatness, stop asking for permission. — Unknown",
  "The comeback is always stronger than the setback. — Unknown",
  "Don’t wish it were easier. Wish you were better. — Jim Rohn",
  "A warrior’s greatest weapon is patience. — Miyamoto Musashi",
  "Your life does not get better by chance, it gets better by change. — Jim Rohn",
  "Storms make trees take deeper roots. — Dolly Parton",
  "There are no shortcuts to any place worth going. — Beverly Sills",
  "A diamond is a chunk of coal that did well under pressure. — Henry Kissinger",
  "You have power over your mind, not outside events. — Marcus Aurelius",
  "You don’t drown by falling in water; you drown by staying there. — Edwin Louis Cole",
  "The battle is won before it is fought. — Sun Tzu",
  "No pressure, no diamonds. — Thomas Carlyle",
  "Turn your wounds into wisdom. — Oprah Winfrey",
  "Work until your idols become your rivals. — Drake",
  "If you don’t walk today, you’ll have to run tomorrow. — Unknown",
  "Get up with determination if you’re going to go to bed with satisfaction. — George Lorimer",
  "Act like the person you want to become. — Unknown",
  "Ambition is the first step to success. — Unknown",
  "Become obsessed with your goals. — Unknown",
  "Build yourself so strong that nobody can break you. — Unknown",
  "Chase progress, not approval. — Unknown",
  "Confidence comes from preparation. — Unknown",
  "Decide. Commit. Succeed. — Unknown",
  "Discomfort is where growth begins. — Unknown",
  "Do it tired. Do it scared. Just do it. — Unknown",
  "Everything you want is on the other side of fear. — Jack Canfield",
  "Failure is not the opposite of success. It’s part of it. — Unknown",
  "Greatness takes sacrifice. — Unknown",
  "Keep your standards high. — Unknown",
  "Learn to rest, not quit. — Banksy",
  "Make your younger self proud. — Unknown",
  "Mindset is everything. — Unknown",
  "One decision can change your life. — Unknown",
  "Self-discipline is self-respect. — Unknown",
  "Silence the doubt with results. — Unknown",
  "Slow progress is still progress. — Unknown",
  "Stay focused on your mission. — Unknown",
  "Success begins at the end of your comfort zone. — Neale Donald Walsch",
  "Take the risk or lose the chance. — Unknown",
  "Trust the process. — Unknown",
  "Wake up with determination. — Unknown",
  "Win the morning, win the day. — Tim Ferriss",
  "Your grind will pay off. — Unknown",
  "You grow through what you go through. — Unknown",
  "Discipline creates freedom. — Jocko Willink",
  "Pressure builds champions. — Unknown",
  "Dream bigger. Work harder. — Unknown",
  "A winner is just a loser who kept trying. — Unknown",
  "The grind never lies. — Unknown",
  "Stay consistent and unstoppable. — Unknown",
  "Outwork your old self. — Unknown",
  "Don’t fear being different. — Unknown",
  "Turn your pain into power. — Unknown",
  "Your limits are mental. — Unknown",
  "Never settle for less. — Unknown",
  "Stay patient and trust your timing. — Unknown",
  "Make discipline your lifestyle. — Unknown",
  "Success is a mindset. — Unknown",
  "Prove yourself to yourself. — Unknown",
  "Doubt kills more dreams than failure. — Suzy Kassem",
  "The work you avoid is the work you need. — Unknown",
  "Success rewards consistency. — Unknown",
  "You are your only limit. — Unknown",
  "Strong habits build strong futures. — Unknown",
  "Be fearless in pursuit of your goals. — Unknown",
  "Turn ambition into reality. — Unknown",
  "One more rep. One more try. One more day. — Unknown",
  "You can do hard things. — Unknown",
  "You didn’t come this far just to come this far. — Unknown",
  "Small steps every day become massive results. — Unknown",
  "Pain is temporary. Pride is forever. — Unknown",
  "Winners are made when nobody is watching. — Unknown",
  "Great things take time. — Unknown",
  "Your only competition is who you were yesterday. — Unknown",
  "Every master was once a beginner. — Unknown",
  "Make yourself impossible to ignore. — Steve Martin",
  "The grind may be hard, but regret is harder. — Unknown",
  "Don’t wait for opportunity. Create it. — George Bernard Shaw",
  "Consistency creates confidence. — Unknown",
  "No risk, no story. — Unknown",
  "Energy flows where focus goes. — Tony Robbins",
  "Turn pressure into power. — Unknown",
  "Stay hungry. Stay ambitious. — Unknown",
  "Success loves consistency. — Unknown",
  "A little progress each day adds up to big results. — Satya Nani",
  "Be obsessed with your own potential. — Unknown",
  "The man who loves walking will go further than the man who loves the destination. — Unknown",
  "Be the person your enemies fear you will become. — Unknown",
  "Hard work is a talent. — Cristiano Ronaldo",
  "The version of you that doesn't quit is unstoppable. — Unknown",
  "Stop waiting for permission; start creating results. — Unknown",
  "Discipline is the highest form of self-love. — Unknown",

"The greatest battle is the war against ignorance. — Mustafa Kemal Atatürk",

"Peace at home, peace in the world. — Mustafa Kemal Atatürk",

"The impediment to action advances action. — Marcus Aurelius",

"He who conquers himself is the mightiest warrior. — Confucius",

"Do not fear failure but rather fear not trying. — Roy T. Bennett",

"Be tolerant with others and strict with yourself. — Marcus Aurelius",

"The soul becomes dyed with the color of its thoughts. — Marcus Aurelius",

"Knowing is not enough, we must apply. — Goethe",

"Take a rest; a field that has rested gives a beautiful crop. — Ovid",

"Absorb what is useful. Reject what is useless. — Bruce Lee",

"I hated every minute of training, but I said: don’t quit. — Muhammad Ali",

"Talent without working hard is nothing. — Cristiano Ronaldo",

"Life opens up opportunities to you, and you either take them or you stay afraid. — Jim Carrey",

"Desperation is a necessary ingredient to learning anything. — Jim Carrey",

"If you want to shine like a sun, first burn like a sun. — A. P. J. Abdul Kalam",

"The people who are crazy enough to think they can change the world are the ones who do. — Steve Jobs",

"The future belongs to those who believe in the beauty of their dreams. — Eleanor Roosevelt",

"The only true wisdom is in knowing you know nothing. — Socrates",

"The successful warrior is the average man with laser-like focus. — Bruce Lee",

];