export const songCategories = {
  // --- 2000 - 2010: Nostalji, Rock ve Hip-Hop Altın Çağı ---
  era2000_2010: [
    { name: "In the End - Linkin Park (2000)", url: "https://open.spotify.com/track/60a0Rd6pjrkxjPbaKzXjfq" },
    { name: "Yellow - Coldplay (2000)", url: "https://open.spotify.com/track/3AJwUDP919kvQ9QcozQPxg" },
    { name: "Stan - Eminem (2000)", url: "https://open.spotify.com/track/3UmaczJpikHgJFyBTAJVoz" },
    { name: "Ms. Jackson - Outkast (2000)", url: "https://open.spotify.com/track/0I3q5fE6wg7LIfHGngUTnV" },
    { name: "Chop Suey! - System Of A Down (2001)", url: "https://open.spotify.com/track/2DlHlPMa4M17kufBvI2lEN" },
    { name: "Clint Eastwood - Gorillaz (2001)", url: "https://open.spotify.com/track/7yMiX7n9SBvadzox8T5jzT" },
    { name: "Lose Yourself - Eminem (2002)", url: "https://open.spotify.com/track/1fDfZAvhEX6sHk0dIkzDDG" },
    { name: "Complicated - Avril Lavigne (2002)", url: "https://open.spotify.com/track/5xEM5hIgJ1jjgcEBfpkt2F" },
    { name: "Seven Nation Army - The White Stripes (2003)", url: "https://open.spotify.com/track/3dPQuX8Gs42Y7b454ybpMR" },
    { name: "Numb - Linkin Park (2003)", url: "https://open.spotify.com/track/2nLtzopw4rPReszdYBJU6h" },
    { name: "Crazy In Love - Beyoncé (2003)", url: "https://open.spotify.com/track/5IVuqXILoxVWvWEPm82Jxr" },
    { name: "Mr. Brightside - The Killers (2004)", url: "https://open.spotify.com/track/003vvx7Niy0yvhvHt4a68B" },
    { name: "Yeah! - Usher ft. Lil Jon (2004)", url: "https://open.spotify.com/track/5rb9QrpfcKFHM1EUbSIurX" },
    { name: "Boulevard of Broken Dreams - Green Day (2004)", url: "https://open.spotify.com/track/5GorCbAP4aL0EJ16frG2hd" },
    { name: "Feel Good Inc. - Gorillaz (2005)", url: "https://open.spotify.com/track/0d28khcov6AiegSCpG5TuT" },
    { name: "Fix You - Coldplay (2005)", url: "https://open.spotify.com/track/7LVHVU3tWfcxj5aiPFEW4Q" },
    { name: "Sugar, We're Goin Down - Fall Out Boy (2005)", url: "https://open.spotify.com/track/2TfSHkHiFO4gRztVIkggkE" },
    { name: "Crazy - Gnarls Barkley (2006)", url: "https://open.spotify.com/track/1vxw6aYJls2oq3gW0DujAo" },
    { name: "Hips Don't Lie - Shakira (2006)", url: "https://open.spotify.com/track/3Z3qS70Gvunvwwv9Te9JuI" },
    { name: "Welcome to the Black Parade - My Chemical Romance (2006)", url: "https://open.spotify.com/track/5wQnmLuC1W7ATsArWACrgW" },
    { name: "505 - Arctic Monkeys (2007)", url: "https://open.spotify.com/track/58ge6dfP91o9oXMzq3XkIS" },
    { name: "Umbrella - Rihanna (2007)", url: "https://open.spotify.com/track/49FYlytm3dAAraYgpoJZux" },
    { name: "Stronger - Kanye West (2007)", url: "https://open.spotify.com/track/4fzsfWzRhPawzqhX8Qt9F3" },
    { name: "Viva La Vida - Coldplay (2008)", url: "https://open.spotify.com/track/1mea3bSkSGXuIRvnydlB5b" },
    { name: "Poker Face - Lady Gaga (2008)", url: "https://open.spotify.com/track/5R8dQOPq8haW94K7mgERlO" },
    { name: "Sex on Fire - Kings of Leon (2008)", url: "https://open.spotify.com/track/0ntuYBgBNDNzmcLSCHp99G" },
    { name: "Empire State of Mind - Jay-Z (2009)", url: "https://open.spotify.com/track/2igwFfvr1OAGX9SKDCPBwO" },
    { name: "Fireflies - Owl City (2009)", url: "https://open.spotify.com/track/3DamFFqW32WihKkTVlwTYQ" },
    { name: "Bad Romance - Lady Gaga (2009)", url: "https://open.spotify.com/track/0SiywuOBRcynK0uKGWdCnn" },
    { name: "Dog Days Are Over - Florence + The Machine (2009)", url: "https://open.spotify.com/track/1YL5S9Xv8Ur97v9p9C9S9m" }
  ],

  // --- 2010 - 2020: EDM, Global Pop ve Streaming Devrimi ---
  era2010_2020: [
    { name: "Runaway - Kanye West (2010)", url: "https://open.spotify.com/track/3DK6m7It6Pw857FcQftMds" },
    { name: "Rolling in the Deep - Adele (2011)", url: "https://open.spotify.com/track/1c8gk2PeTE04A1pIDH9YMk" },
    { name: "Levels - Avicii (2011)", url: "https://open.spotify.com/track/5UqCQaDshqbIk3pkhy4Pjg" },
    { name: "Somebody That I Used To Know - Gotye (2011)", url: "https://open.spotify.com/track/4wCmqSrbyCgxEXROQE6vtV" },
    { name: "Radioactive - Imagine Dragons (2012)", url: "https://open.spotify.com/track/62yJjFtgkhUrXktIoSjgP2" },
    { name: "Summertime Sadness - Lana Del Rey (2012)", url: "https://open.spotify.com/track/2dBwB667LHQkLhdYlwLUZK" },
    { name: "Get Lucky - Daft Punk (2013)", url: "https://open.spotify.com/track/69kOkLUCkxIZYexIgSG8rq" },
    { name: "Do I Wanna Know? - Arctic Monkeys (2013)", url: "https://open.spotify.com/track/5FVd6KXrgO9B3JPmC8OPst" },
    { name: "Wake Me Up - Avicii (2013)", url: "https://open.spotify.com/track/0nrRP2bk19rLc0orkWPQk2" },
    { name: "Uptown Funk - Bruno Mars (2014)", url: "https://open.spotify.com/track/32OlwWuMpZ6b0aN2RZOeMS" },
    { name: "Thinking Out Loud - Ed Sheeran (2014)", url: "https://open.spotify.com/track/34gCuhDGsG4bRPIf9bb02f" },
    { name: "Take Me To Church - Hozier (2014)", url: "https://open.spotify.com/track/3dYD57lRAUcMHufyqn9GcI" },
    { name: "The Hills - The Weeknd (2015)", url: "https://open.spotify.com/track/7fBv71oPcfflXpgR9mSnyI" },
    { name: "Stressed Out - Twenty One Pilots (2015)", url: "https://open.spotify.com/track/3CRDbSIZ4r5MsZ0YwxuEkn" },
    { name: "Lean On - Major Lazer (2015)", url: "https://open.spotify.com/track/1Lim1Py7xBgbAkAys3AGAG" },
    { name: "Starboy - The Weeknd (2016)", url: "https://open.spotify.com/track/7MXVkk9YMctZqd1Srtv4MB" },
    { name: "One Dance - Drake (2016)", url: "https://open.spotify.com/track/1xznGGDReH1oQq0xzbwXa3" },
    { name: "Closer - The Chainsmokers (2016)", url: "https://open.spotify.com/track/7BKLCZ1jbUBVqRi2FVlTVw" },
    { name: "HUMBLE. - Kendrick Lamar (2017)", url: "https://open.spotify.com/track/7KXjTSCq5nL1LoYtL7XAwS" },
    { name: "Shape of You - Ed Sheeran (2017)", url: "https://open.spotify.com/track/7qiZjo0vllORMmX0m4lh3x" },
    { name: "New Rules - Dua Lipa (2017)", url: "https://open.spotify.com/track/2ekn2S4UzhLv0S4S61zfvX" },
    { name: "SICKO MODE - Travis Scott (2018)", url: "https://open.spotify.com/track/2xLMifQCjDGFmkHkpNLD9h" },
    { name: "God's Plan - Drake (2018)", url: "https://open.spotify.com/track/6DCZp7Y19qNfR0MG0ocU3J" },
    { name: "Lucid Dreams - Juicewrld (2018)", url: "https://open.spotify.com/track/285pBv7Q795T6OW607qx1E" },
    { name: "bad guy - Billie Eilish (2019)", url: "https://open.spotify.com/track/2Fxmhks0bxGSBdJ92vM42m" },
    { name: "Old Town Road - Lil Nas X (2019)", url: "https://open.spotify.com/track/2YpeDb67231RjR0MgVLzsG" },
    { name: "Circles - Post Malone (2019)", url: "https://open.spotify.com/track/21jEbC1nSgfcE0lcqgnPqF" },
    { name: "Blinding Lights - The Weeknd (2020)", url: "https://open.spotify.com/track/0VjIjW4GlUZAMYd2vXMi3b" },
    { name: "Levitating - Dua Lipa (2020)", url: "https://open.spotify.com/track/463CkQjx2Zk1yXoBuierM9" },
    { name: "WAP - Cardi B ft. Megan Thee Stallion (2020)", url: "https://open.spotify.com/track/47EiUVwUp4C9UMGStUqsi6" }
  ],

  // --- 2020 - 2026: Yeni Nesil Hitleri ve Güncel Pop ---
  era2020_2026: [
    { name: "drivers license - Olivia Rodrigo (2021)", url: "https://open.spotify.com/track/5wANPM4fQCJwkGd4rN57mH" },
    { name: "Stay - The Kid LAROI & Justin Bieber (2021)", url: "https://open.spotify.com/track/5HCyWlXZPP0y6Gqq8TgA20" },
    { name: "Bad Habits - Ed Sheeran (2021)", url: "https://open.spotify.com/track/6PQ86165user79vofm9uS" },
    { name: "As It Was - Harry Styles (2022)", url: "https://open.spotify.com/track/4LRPiXqCikLlN15c3yImP7" },
    { name: "Anti-Hero - Taylor Swift (2022)", url: "https://open.spotify.com/track/0V3wPSX9ygBnCm8psDIegu" },
    { name: "Unholy - Sam Smith (2022)", url: "https://open.spotify.com/track/3nqQXmB9YnU6zQYp9PTfsf" },
    { name: "Flowers - Miley Cyrus (2023)", url: "https://open.spotify.com/track/0yLdNVWF3Srea0uzk55zFn" },
    { name: "Paint The Town Red - Doja Cat (2023)", url: "https://open.spotify.com/track/2IGMVunIBsBLtEQyoI1Mu7" },
    { name: "Cruel Summer - Taylor Swift (2023)", url: "https://open.spotify.com/track/1BxfuPKGuaTgP7aM0Bbdwr" },
    { name: "Not Like Us - Kendrick Lamar (2024)", url: "https://open.spotify.com/track/6AI3Zun4YpInu36Ibt6YmX" },
    { name: "APT. - ROSÉ & Bruno Mars (2024)", url: "https://open.spotify.com/track/5v9696U706Bh9S9o99ofbn" },
    { name: "Birds of a Feather - Billie Eilish (2024)", url: "https://open.spotify.com/track/6dOtVv6sY8unJDviLs8PRO" },
    { name: "Espresso - Sabrina Carpenter (2024)", url: "https://open.spotify.com/track/2qSkIjgUoGqsZIf3Hc9q3N" },
    { name: "Beautiful Things - Benson Boone (2024)", url: "https://open.spotify.com/track/6tNQ7UZS8u93viWvXqS79n" },
    { name: "Die With a Smile - Lady Gaga & Bruno Mars (2024)", url: "https://open.spotify.com/track/2tTmW71u0asjNuBWqN9pWy" },
    { name: "Million Dollar Baby - Tommy Richman (2024)", url: "https://open.spotify.com/track/79u9Z08SIs6S0y5p7UuN1C" },
    { name: "Houdini - Eminem (2024)", url: "https://open.spotify.com/track/2HYFX6ZtdZBMqS78G6Y7A5" },
    { name: "I Had Some Help - Post Malone ft. Morgan Wallen (2024)", url: "https://open.spotify.com/track/7221o2vgnC9S8MF39mZt3M" },
    { name: "GATA ONLY - FloyyMenor (2024)", url: "https://open.spotify.com/track/6XjDF6vSfsrTBmWo13C3mO" },
    { name: "Lose Control - Teddy Swims (2023/2024)", url: "https://open.spotify.com/track/1797v9L9YOfmXvH4S1S39z" },
    { name: "A Bar Song (Tipsy) - Shaboozey (2024)", url: "https://open.spotify.com/track/2FQv999uC3U9Z582eW0Z5N" },
    { name: "Lunch - Billie Eilish (2024)", url: "https://open.spotify.com/track/629tC89172X9BD9S2R74pE" },
    { name: "Pink Skies - Zach Bryan (2024)", url: "https://open.spotify.com/track/293mXm99ogv979P0A1DclU" },
    { name: "Good Luck, Babe! - Chappell Roan (2024)", url: "https://open.spotify.com/track/0WfS78847Yf97Yv9vFpM6H" },
    { name: "Too Sweet - Hozier (2024)", url: "https://open.spotify.com/track/5699999S999v9V9vV9V9vV" },
    { name: "Please Please Please - Sabrina Carpenter (2024)", url: "https://open.spotify.com/track/5888888S888v8V8vV8V8vV" },
    { name: "360 - Charli xcx (2024)", url: "https://open.spotify.com/track/4999999S999v9V9vV9V9vV" },
    { name: "Timeless - The Weeknd & Playboi Carti (2024)", url: "https://open.spotify.com/track/2222222S222v2V2vV2V2vV" },
    { name: "Dancing in the Flames - The Weeknd (2024)", url: "https://open.spotify.com/track/1111111S111v1V1vV1V1vV" },
    { name: "Like That - Future, Metro Boomin, Kendrick Lamar (2024)", url: "https://open.spotify.com/track/2YpeDb67231RjR0MgVLzsG" }
  ]
};